/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AIEscrowMarketplace {
  export type BidStruct = {
    bidId: BigNumberish;
    jobId: BigNumberish;
    freelancer: AddressLike;
    proposalText: string;
  };

  export type BidStructOutput = [
    bidId: bigint,
    jobId: bigint,
    freelancer: string,
    proposalText: string
  ] & {
    bidId: bigint;
    jobId: bigint;
    freelancer: string;
    proposalText: string;
  };
}

export interface AIEscrowMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptBid"
      | "aiAgentAddress"
      | "bidsByJobId"
      | "depositForJob"
      | "getBidsForJob"
      | "getJobCount"
      | "jobs"
      | "jobsByClient"
      | "jobsByFreelancer"
      | "nextJobId"
      | "owner"
      | "postJob"
      | "renounceOwnership"
      | "setAiAgentAddress"
      | "submitBid"
      | "submitWork"
      | "transferOwnership"
      | "verifyWork"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AiAgentAddressUpdated"
      | "BidAccepted"
      | "BidSubmitted"
      | "FundsDeposited"
      | "FundsReleased"
      | "JobPosted"
      | "OwnershipTransferred"
      | "WorkSubmitted"
      | "WorkVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptBid",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "aiAgentAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bidsByJobId",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositForJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidsForJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "jobsByClient",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "jobsByFreelancer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nextJobId", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postJob",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAiAgentAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBid",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitWork",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyWork",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "acceptBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "aiAgentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bidsByJobId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositForJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBidsForJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJobCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "jobsByClient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "jobsByFreelancer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextJobId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAiAgentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitWork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyWork", data: BytesLike): Result;
}

export namespace AiAgentAddressUpdatedEvent {
  export type InputTuple = [newAddress: AddressLike];
  export type OutputTuple = [newAddress: string];
  export interface OutputObject {
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidAcceptedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    bidId: BigNumberish,
    client: AddressLike,
    freelancer: AddressLike
  ];
  export type OutputTuple = [
    jobId: bigint,
    bidId: bigint,
    client: string,
    freelancer: string
  ];
  export interface OutputObject {
    jobId: bigint;
    bidId: bigint;
    client: string;
    freelancer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidSubmittedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    bidId: BigNumberish,
    freelancer: AddressLike,
    proposalText: string
  ];
  export type OutputTuple = [
    jobId: bigint,
    bidId: bigint,
    freelancer: string,
    proposalText: string
  ];
  export interface OutputObject {
    jobId: bigint;
    bidId: bigint;
    freelancer: string;
    proposalText: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDepositedEvent {
  export type InputTuple = [jobId: BigNumberish, price: BigNumberish];
  export type OutputTuple = [jobId: bigint, price: bigint];
  export interface OutputObject {
    jobId: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    recipient: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, recipient: string, price: bigint];
  export interface OutputObject {
    jobId: bigint;
    recipient: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobPostedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    client: AddressLike,
    title: string,
    price: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    client: string,
    title: string,
    price: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    client: string;
    title: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkSubmittedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    freelancer: AddressLike,
    resultIPFSHash: string
  ];
  export type OutputTuple = [
    jobId: bigint,
    freelancer: string,
    resultIPFSHash: string
  ];
  export interface OutputObject {
    jobId: bigint;
    freelancer: string;
    resultIPFSHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkVerifiedEvent {
  export type InputTuple = [jobId: BigNumberish, isApproved: boolean];
  export type OutputTuple = [jobId: bigint, isApproved: boolean];
  export interface OutputObject {
    jobId: bigint;
    isApproved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AIEscrowMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): AIEscrowMarketplace;
  waitForDeployment(): Promise<this>;

  interface: AIEscrowMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptBid: TypedContractMethod<
    [_jobId: BigNumberish, _bidId: BigNumberish],
    [void],
    "nonpayable"
  >;

  aiAgentAddress: TypedContractMethod<[], [string], "view">;

  bidsByJobId: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, string, string] & {
        bidId: bigint;
        jobId: bigint;
        freelancer: string;
        proposalText: string;
      }
    ],
    "view"
  >;

  depositForJob: TypedContractMethod<[_jobId: BigNumberish], [void], "payable">;

  getBidsForJob: TypedContractMethod<
    [_jobId: BigNumberish],
    [AIEscrowMarketplace.BidStructOutput[]],
    "view"
  >;

  getJobCount: TypedContractMethod<[], [bigint], "view">;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, bigint, string, bigint] & {
        client: string;
        freelancer: string;
        title: string;
        descriptionIPFSHash: string;
        price: bigint;
        deadline: bigint;
        resultIPFSHash: string;
        status: bigint;
      }
    ],
    "view"
  >;

  jobsByClient: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  jobsByFreelancer: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  nextJobId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  postJob: TypedContractMethod<
    [
      _title: string,
      _descriptionIPFSHash: string,
      _price: BigNumberish,
      _deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAiAgentAddress: TypedContractMethod<
    [_newAiAgentAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  submitBid: TypedContractMethod<
    [_jobId: BigNumberish, _proposalText: string],
    [void],
    "nonpayable"
  >;

  submitWork: TypedContractMethod<
    [_jobId: BigNumberish, _resultIPFSHash: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyWork: TypedContractMethod<
    [_jobId: BigNumberish, _isApproved: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptBid"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _bidId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "aiAgentAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bidsByJobId"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, string, string] & {
        bidId: bigint;
        jobId: bigint;
        freelancer: string;
        proposalText: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositForJob"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getBidsForJob"
  ): TypedContractMethod<
    [_jobId: BigNumberish],
    [AIEscrowMarketplace.BidStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJobCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, bigint, string, bigint] & {
        client: string;
        freelancer: string;
        title: string;
        descriptionIPFSHash: string;
        price: bigint;
        deadline: bigint;
        resultIPFSHash: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobsByClient"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobsByFreelancer"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextJobId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postJob"
  ): TypedContractMethod<
    [
      _title: string,
      _descriptionIPFSHash: string,
      _price: BigNumberish,
      _deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAiAgentAddress"
  ): TypedContractMethod<
    [_newAiAgentAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitBid"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _proposalText: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitWork"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _resultIPFSHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyWork"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _isApproved: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AiAgentAddressUpdated"
  ): TypedContractEvent<
    AiAgentAddressUpdatedEvent.InputTuple,
    AiAgentAddressUpdatedEvent.OutputTuple,
    AiAgentAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BidAccepted"
  ): TypedContractEvent<
    BidAcceptedEvent.InputTuple,
    BidAcceptedEvent.OutputTuple,
    BidAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "BidSubmitted"
  ): TypedContractEvent<
    BidSubmittedEvent.InputTuple,
    BidSubmittedEvent.OutputTuple,
    BidSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "FundsDeposited"
  ): TypedContractEvent<
    FundsDepositedEvent.InputTuple,
    FundsDepositedEvent.OutputTuple,
    FundsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "JobPosted"
  ): TypedContractEvent<
    JobPostedEvent.InputTuple,
    JobPostedEvent.OutputTuple,
    JobPostedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WorkSubmitted"
  ): TypedContractEvent<
    WorkSubmittedEvent.InputTuple,
    WorkSubmittedEvent.OutputTuple,
    WorkSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "WorkVerified"
  ): TypedContractEvent<
    WorkVerifiedEvent.InputTuple,
    WorkVerifiedEvent.OutputTuple,
    WorkVerifiedEvent.OutputObject
  >;

  filters: {
    "AiAgentAddressUpdated(address)": TypedContractEvent<
      AiAgentAddressUpdatedEvent.InputTuple,
      AiAgentAddressUpdatedEvent.OutputTuple,
      AiAgentAddressUpdatedEvent.OutputObject
    >;
    AiAgentAddressUpdated: TypedContractEvent<
      AiAgentAddressUpdatedEvent.InputTuple,
      AiAgentAddressUpdatedEvent.OutputTuple,
      AiAgentAddressUpdatedEvent.OutputObject
    >;

    "BidAccepted(uint256,uint256,address,address)": TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;
    BidAccepted: TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;

    "BidSubmitted(uint256,uint256,address,string)": TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
    BidSubmitted: TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;

    "FundsDeposited(uint256,uint256)": TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;
    FundsDeposited: TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;

    "FundsReleased(uint256,address,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "JobPosted(uint256,address,string,uint256)": TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;
    JobPosted: TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WorkSubmitted(uint256,address,string)": TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;
    WorkSubmitted: TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;

    "WorkVerified(uint256,bool)": TypedContractEvent<
      WorkVerifiedEvent.InputTuple,
      WorkVerifiedEvent.OutputTuple,
      WorkVerifiedEvent.OutputObject
    >;
    WorkVerified: TypedContractEvent<
      WorkVerifiedEvent.InputTuple,
      WorkVerifiedEvent.OutputTuple,
      WorkVerifiedEvent.OutputObject
    >;
  };
}
