/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AIEscrowMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "aiAgentAddress"
      | "createJob"
      | "depositFunds"
      | "jobs"
      | "nextJobId"
      | "owner"
      | "renounceOwnership"
      | "setAiAgentAddress"
      | "submitWork"
      | "transferOwnership"
      | "verifyWork"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AiAgentAddressUpdated"
      | "FundsDeposited"
      | "FundsReleased"
      | "JobCreated"
      | "OwnershipTransferred"
      | "WorkSubmitted"
      | "WorkVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "aiAgentAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "nextJobId", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAiAgentAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitWork",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyWork",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "aiAgentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextJobId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAiAgentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitWork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyWork", data: BytesLike): Result;
}

export namespace AiAgentAddressUpdatedEvent {
  export type InputTuple = [newAddress: AddressLike];
  export type OutputTuple = [newAddress: string];
  export interface OutputObject {
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDepositedEvent {
  export type InputTuple = [jobId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [jobId: bigint, amount: bigint];
  export interface OutputObject {
    jobId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, recipient: string, amount: bigint];
  export interface OutputObject {
    jobId: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    client: AddressLike,
    freelancer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    client: string,
    freelancer: string,
    amount: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    client: string;
    freelancer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkSubmittedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    freelancer: AddressLike,
    resultIPFSHash: string
  ];
  export type OutputTuple = [
    jobId: bigint,
    freelancer: string,
    resultIPFSHash: string
  ];
  export interface OutputObject {
    jobId: bigint;
    freelancer: string;
    resultIPFSHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkVerifiedEvent {
  export type InputTuple = [jobId: BigNumberish, isApproved: boolean];
  export type OutputTuple = [jobId: bigint, isApproved: boolean];
  export interface OutputObject {
    jobId: bigint;
    isApproved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AIEscrowMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): AIEscrowMarketplace;
  waitForDeployment(): Promise<this>;

  interface: AIEscrowMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  aiAgentAddress: TypedContractMethod<[], [string], "view">;

  createJob: TypedContractMethod<
    [
      _freelancer: AddressLike,
      _amount: BigNumberish,
      _workDescriptionIPFSHash: string
    ],
    [void],
    "nonpayable"
  >;

  depositFunds: TypedContractMethod<[_jobId: BigNumberish], [void], "payable">;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, string, bigint] & {
        client: string;
        freelancer: string;
        amount: bigint;
        workDescriptionIPFSHash: string;
        resultIPFSHash: string;
        status: bigint;
      }
    ],
    "view"
  >;

  nextJobId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAiAgentAddress: TypedContractMethod<
    [_newAiAgentAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  submitWork: TypedContractMethod<
    [_jobId: BigNumberish, _resultIPFSHash: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyWork: TypedContractMethod<
    [_jobId: BigNumberish, _isApproved: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "aiAgentAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [
      _freelancer: AddressLike,
      _amount: BigNumberish,
      _workDescriptionIPFSHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositFunds"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, string, bigint] & {
        client: string;
        freelancer: string;
        amount: bigint;
        workDescriptionIPFSHash: string;
        resultIPFSHash: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextJobId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAiAgentAddress"
  ): TypedContractMethod<
    [_newAiAgentAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitWork"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _resultIPFSHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyWork"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _isApproved: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AiAgentAddressUpdated"
  ): TypedContractEvent<
    AiAgentAddressUpdatedEvent.InputTuple,
    AiAgentAddressUpdatedEvent.OutputTuple,
    AiAgentAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FundsDeposited"
  ): TypedContractEvent<
    FundsDepositedEvent.InputTuple,
    FundsDepositedEvent.OutputTuple,
    FundsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WorkSubmitted"
  ): TypedContractEvent<
    WorkSubmittedEvent.InputTuple,
    WorkSubmittedEvent.OutputTuple,
    WorkSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "WorkVerified"
  ): TypedContractEvent<
    WorkVerifiedEvent.InputTuple,
    WorkVerifiedEvent.OutputTuple,
    WorkVerifiedEvent.OutputObject
  >;

  filters: {
    "AiAgentAddressUpdated(address)": TypedContractEvent<
      AiAgentAddressUpdatedEvent.InputTuple,
      AiAgentAddressUpdatedEvent.OutputTuple,
      AiAgentAddressUpdatedEvent.OutputObject
    >;
    AiAgentAddressUpdated: TypedContractEvent<
      AiAgentAddressUpdatedEvent.InputTuple,
      AiAgentAddressUpdatedEvent.OutputTuple,
      AiAgentAddressUpdatedEvent.OutputObject
    >;

    "FundsDeposited(uint256,uint256)": TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;
    FundsDeposited: TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;

    "FundsReleased(uint256,address,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "JobCreated(uint256,address,address,uint256)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WorkSubmitted(uint256,address,string)": TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;
    WorkSubmitted: TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;

    "WorkVerified(uint256,bool)": TypedContractEvent<
      WorkVerifiedEvent.InputTuple,
      WorkVerifiedEvent.OutputTuple,
      WorkVerifiedEvent.OutputObject
    >;
    WorkVerified: TypedContractEvent<
      WorkVerifiedEvent.InputTuple,
      WorkVerifiedEvent.OutputTuple,
      WorkVerifiedEvent.OutputObject
    >;
  };
}
